feat: added OG tags
Pujo-Atlas-Kolkata/PujoAtlasKol-Web pull request #167
Opened 2024-10-05 08:51 UTC by yashchaurasia667

Closes #<issue>

## Checklist

- [x] I have followed every step in the [contributing guide](https://github.com/Pujo-Atlas-Kolkata/PujoAtlasKol-Web/blob/dev/CONTRIBUTING.md)
- [x] The PR title follows the convention we established [conventional-commit](https://www.conventionalcommits.org/en/v1.0.0/)
- [x] I performed a functional test on my final commit

---

## Changelog

added default og tags and twitter meta tags

---

## Screenshots

2024-10-05 09:14 UTC, wriddhi requested changes

2024-10-05 09:14 UTC, wriddhi commented on src/layouts/LandingPageLayout.astro
> +  content = 'https://i.pinimg.com/564x/17/ef/f5/17eff5d4df16b95d8a30184f57a13ed5.jpg',
```suggestion
  image = 'https://i.pinimg.com/564x/17/ef/f5/17eff5d4df16b95d8a30184f57a13ed5.jpg',
```

2024-10-05 09:14 UTC, wriddhi commented on src/layouts/LandingPageLayout.astro
> +  content?: string;
```suggestion
  image?: string;
```

2024-10-05 09:14 UTC, wriddhi commented on src/layouts/LandingPageLayout.astro
> +    <meta property="og:image" content={content} />
```suggestion
    <meta property="og:image" content={image} />
```

2024-10-05 09:14 UTC, wriddhi commented on src/layouts/LandingPageLayout.astro
> +    <meta name="twitter:image" content={content} />
```suggestion
    <meta name="twitter:image" content={image} />
```

2024-10-07 09:39 UTC, AyanavaKarmakar commented on src/layouts/LandingPageLayout.astro
> +  image = 'https://i.pinimg.com/564x/17/ef/f5/17eff5d4df16b95d8a30184f57a13ed5.jpg',
```suggestion
  image = 'https://cdn.discordapp.com/attachments/1279856563112382529/1292782921534410835/2.png?ex=6704fd6b&is=6703abeb&hm=6f477b8f191bdb0ff5280ccec699434260900565ef2bd0d820409d3acdd13a86&',
```

2024-10-08 11:56 UTC, AyanavaKarmakar approved these changes

2024-10-08 11:57 UTC, merged